name: linting, testing, building
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
permissions:
    contents: write
    pages: write
    id-token: write
concurrency:
    group: 'pages'
    cancel-in-progress: true
jobs:
    checks:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.16.0]
        steps:
            - uses: actions/checkout@v2

            - name: Staring Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: install modules
              run: npm ci --force

            - name: linting typescript
              run: npm run lint:ts
              if: always()

            - name: linting css
              run: npm run lint:css

            - name: unit testing
              if: always()
              run: npm run test:unit
